// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package mongo

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MongoStringTag struct {
	_tab flatbuffers.Table
}

func GetRootAsMongoStringTag(buf []byte, offset flatbuffers.UOffsetT) *MongoStringTag {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MongoStringTag{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMongoStringTag(buf []byte, offset flatbuffers.UOffsetT) *MongoStringTag {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MongoStringTag{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *MongoStringTag) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MongoStringTag) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MongoStringTag) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MongoStringTagStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MongoStringTagAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(value), 0)
}
func MongoStringTagEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
