// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package mongo

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MongoTag struct {
	_tab flatbuffers.Table
}

func GetRootAsMongoTag(buf []byte, offset flatbuffers.UOffsetT) *MongoTag {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MongoTag{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMongoTag(buf []byte, offset flatbuffers.UOffsetT) *MongoTag {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MongoTag{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *MongoTag) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MongoTag) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MongoTag) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MongoTag) ValueType() MongoTagValue {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return MongoTagValue(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MongoTag) MutateValueType(n MongoTagValue) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *MongoTag) Value(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func MongoTagStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MongoTagAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func MongoTagAddValueType(builder *flatbuffers.Builder, valueType MongoTagValue) {
	builder.PrependByteSlot(1, byte(valueType), 0)
}
func MongoTagAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(value), 0)
}
func MongoTagEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
